packages:
  - name: songs
    actions:
      - name: list
        runtime: go:default
        environment:
          DB_USERNAME: "${DB_USERNAME}"
          DB_PASSWORD: "${DB_PASSWORD}"
          DB_HOST: "${DB_HOST}"
          DB_PORT: "${DB_PORT}"
